apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedSecret
metadata:
  name: s3-bucket-owner
  namespace: federation-test
spec:
  template:
    data:
      AWS_ACCESS_KEY_ID: <base64 encoded aws access key>
      AWS_SECRET_ACCESS_KEY: <base64 encoded aws secret key>
    type: Opaque
  placement:
    clusterNames:
    - cluster2
    - cluster1
