kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-s3-provisioner
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - persistentvolumes
  - events
  - secrets
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-s3-provisioner
subjects:
#- kind: Group
#  name: manager # Name is case sensitive
#  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: default
  namespace: s3-provisioner
roleRef:
  kind: ClusterRole
  name: aws-s3-provisioner
  apiGroup: rbac.authorization.k8s.io
---
